#!/usr/local/bin/jython
tick_types = ('''
                0,BID_SIZE
                1,BID_PRICE
                2,ASK_PRICE
                3,ASK_SIZE
                4,LAST_PRICE
                5,LAST_SIZE
                6,HIGH
                7,LOW
                8,VOLUME
                9,CLOSE_PRICE
                10,BID_OPTION_COMPUTATION
                11,ASK_OPTION_COMPUTATION
                12,LAST_OPTION_COMPUTATION
                13,MODEL_OPTION_COMPUTATION
                14,OPEN_TICK
                15,LOW_13_WEEK
                16,HIGH_13_WEEK
                17,LOW_26_WEEK
                18,HIGH_26_WEEK
                19,LOW_52_WEEK
                20,HIGH_52_WEEK
                21,AVG_VOLUME
                22,OPEN_INTEREST
                23,OPTION_HISTORICAL_VOL
                24,OPTION_IMPLIED_VOL
                25,OPTION_BID_EXCH
                26,OPTION_ASK_EXCH
                27,OPTION_CALL_OPEN_INTEREST
                28,OPTION_PUT_OPEN_INTEREST
                29,OPTION_CALL_VOLUME
                30,OPTION_PUT_VOLUME
                31,INDEX_FUTURE_PREMIUM
                32,BID_EXCH
                33,ASK_EXCH
                34,AUCTION_VOLUME
                35,AUCTION_PRICE
                36,AUCTION_IMBALANCE
                37,MARK_PRICE
                38,BID_EFP_COMPUTATION
                39,ASK_EFP_COMPUTATION
                40,LAST_EFP_COMPUTATION
                41,OPEN_EFP_COMPUTATION
                42,HIGH_EFP_COMPUTATION
                43,LOW_EFP_COMPUTATION
                44,CLOSE_EFP_COMPUTATION
                45,LAST_TIMESTAMP
                46,SHORTABLE
                47,FUNDAMENTAL_RATIOS
                48,RT_VOLUME
                49,HALTED
                50,BIDYIELD
                51,ASKYIELD
                52,LASTYIELD
                53,CUST_OPTION_COMPUTATION
                54,TRADE_COUNT
                55,TRADE_RATE
                56,VOLUME_RATE
''')
